version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  testAndBuild:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
#      - run: npm run test
      - run: npm run build        
        
workflows:
  testAndBuild:
    jobs:
      - testAndBuild
      